[package]
name = "walletconnect-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
serde = "1.0.219"
serde_json = "1.0.140"
url = "2.5.4"
alloy = { version = "0.11", features = ["full", "rlp"] }
rand = "0.8"
ed25519-dalek = "2.1.1"
bs58 = "0.5.1"
